# Nord Theme
# Beautiful arctic, north-bluish color palette

name = "nord"
description = "Nord theme with cool, calming colors"
author = "Zush"
version = "1.0.0"

[colors]
# Nord Polar Night
nord0 = "#2e3440"   # Darkest
nord1 = "#3b4252"   # Dark
nord2 = "#434c5e"   # Medium dark
nord3 = "#4c566a"   # Medium

# Nord Snow Storm
nord4 = "#d8dee9"   # Light
nord5 = "#e5e9f0"   # Lighter
nord6 = "#eceff4"   # Lightest

# Nord Frost
nord7 = "#8fbcbb"   # Frost cyan
nord8 = "#88c0d0"   # Frost blue
nord9 = "#81a1c1"   # Frost dark blue
nord10 = "#5e81ac"  # Frost darkest blue

# Nord Aurora
nord11 = "#bf616a"  # Red
nord12 = "#d08770"  # Orange
nord13 = "#ebcb8b"  # Yellow
nord14 = "#a3be8c"  # Green
nord15 = "#b48ead"  # Purple

[symbols]
prompt_arrow = "❯"
git_branch = ""
folder = ""
separator = ""

[templates]
main = """{{color colors.nord8 ""}} {{color colors.nord8 pwd_short}} {{#if git_branch}}{{color colors.nord15 ""}} {{color colors.nord15 git_branch}}{{#if (gt git_modified 0)}} {{color colors.nord13}}~{{git_modified}}{{/if}}{{#if (gt git_staged 0)}} {{color colors.nord14}}+{{git_staged}}{{/if}}{{#if (gt git_untracked 0)}} {{color colors.nord11}}?{{git_untracked}}{{/if}} {{/if}}
{{#if (eq exit_code 0)}}{{color colors.nord14 "❯"}} {{else}}{{color colors.nord11 "❯"}} {{color colors.nord11 exit_code}} {{color colors.nord11 "❯"}} {{/if}}"""

transient = """{{color colors.nord3 "❯"}} """

right = ""
