# Tokyo Night Theme
# A clean, dark theme inspired by the lights of Tokyo at night

name = "tokyonight"
description = "Tokyo Night theme with vibrant neon colors"
author = "Zush"
version = "1.0.0"

[colors]
# Tokyo Night palette
bg = "#1a1b26"
bg_dark = "#16161e"
bg_highlight = "#292e42"
terminal_black = "#15161e"
fg = "#c0caf5"
fg_dark = "#a9b1d6"
fg_gutter = "#3b4261"
dark3 = "#545c7e"
comment = "#565f89"
dark5 = "#737aa2"
blue0 = "#3d59a1"
blue = "#7aa2f7"
cyan = "#7dcfff"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#b4f9f8"
blue7 = "#394b70"
magenta = "#bb9af7"
magenta2 = "#ff007c"
purple = "#9d7cd8"
orange = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
green1 = "#73daca"
green2 = "#41a6b5"
teal = "#1abc9c"
red = "#f7768e"
red1 = "#db4b4b"

[symbols]
prompt_arrow = "❯"
git_branch = ""
lambda = "λ"
folder = ""
time = ""

[templates]
main = """{{color colors.dark5 ""}} {{color colors.dark5 time}} {{color colors.magenta "λ"}} {{color colors.blue ""}} {{color colors.blue pwd_short}} {{#if git_branch}}{{color colors.green ""}} {{color colors.green git_branch}}{{#if (gt git_modified 0)}} {{color colors.yellow}}~{{git_modified}}{{/if}}{{#if (gt git_staged 0)}} {{color colors.green}}●{{git_staged}}{{/if}}{{#if (gt git_untracked 0)}} {{color colors.red}}?{{git_untracked}}{{/if}}{{#if (gt git_deleted 0)}} {{color colors.red}}-{{git_deleted}}{{/if}} {{/if}}
{{#if (eq exit_code 0)}}{{color colors.cyan "❯"}} {{else}}{{color colors.red "✗"}} {{color colors.red exit_code}} {{color colors.red "❯"}} {{/if}}"""

transient = """{{color colors.fg_gutter "❯"}} """

right = ""
